#!/usr/bin/make -f

debian/scripts/check-language-support /usr/share/kde4/apps/muon/scripts
debian/scripts/language_support_pkgs.py /usr/share/kde4/apps/muon/scripts
debian/scripts/data/check-language-support.1 /usr/share/kde4/apps/muon/scripts/data
debian/scripts/data/pkg_depends /usr/sharekde4/apps/muon/scripts/data
debian/scripts/langtools/language-options /usr/share/kde4/apps/muon/scripts/langtools
debian/scripts/langtools/main-countries /usr/share/kde4/apps/muon/scripts/langtools
